apiVersion: v1
kind: Template
labels:
  component: kibana
  logging-infra: kibana
  provider: openshift
metadata:
  annotations:
    description: Template for deploying log viewer Kibana connecting to ElasticSearch
    tags: infrastructure
  creationTimestamp: null
  labels:
    logging-infra: kibana
  name: kibana-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      component: kibana
      provider: openshift
    name: kibana
  spec:
    replicas: 1
    selector:
      component: kibana
      provider: openshift
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          component: kibana
          provider: openshift
        name: kibana
      spec:
        serviceAccountName: kibana
        containers:
        - env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch.packetbeat.svc.cluster.local:9200
          image: kibana
          imagePullPolicy: Always
          name: kibana
          ports:
          - containerPort: 5601
            name: kibana
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - kibana
        from:
          kind: ImageStreamTag
          name: kibana:${IMAGE_VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: kibana
  spec:
    ports:
    - name: 5601-tcp
      port: 5601
      protocol: TCP
      targetPort: 5601
    selector:
      deploymentconfig: kibana
parameters:
- description: Specify version for kibana
  name: IMAGE_VERSION
  value: latest
